# Generated by Django 5.2.2 on 2025-06-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('chosen', models.TextField()),
                ('rejected', models.TextField()),
            ],
        ),
    ]
